[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 20, in select_next_node
    popularity_weights = [1.0 / (1.0 + unvisited_nodes.count(node)) for node in unvisited_nodes]
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 20, in <listcomp>
    popularity_weights = [1.0 / (1.0 + unvisited_nodes.count(node)) for node in unvisited_nodes]
AttributeError: 'set' object has no attribute 'count'
