[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 28, in select_next_node
    next_node = min(unvisited_nodes, key=hybrid_score)
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 23, in <lambda>
    penalty(node)
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 17, in <lambda>
    penalty = lambda node: 0.3 * min(distance_matrix[current_node][n] for n in unvisited_nodes if n != node)
ValueError: min() arg is an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 30, in select_next_node
    next_node = random.choice(unvisited_nodes)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
TypeError: 'set' object is not subscriptable
