[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 23, in select_next_node
    next_node = random.choices(list(probabilities.keys()), weights=probabilities.values(), k=1)[0]
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 533, in choices
    total = cum_weights[-1] + 0.0   # convert to float
IndexError: list index out of range
