[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 42, in eval_heuristic
    next_node = select_next_node(
  File "D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py", line 41, in select_next_node
    node1, node2 = random.sample(list(unvisited_nodes), 2)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
